ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "repo_name"
  site-url: "https://professorwug.github.io/repo_name"
  description: "Fast, pointwise graph curvature"
  twitter-card: true
  open-graph: true
  repo-branch: main
  repo-url: "https://github.com/professorwug/repo_name"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/professorwug/repo_name"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
